#!/bin/bash

source ./paths.sh

cat $PATH_CHARACTER_SPELL_ABILITIES_EXLPANATION >> $OUTPUT_CHARACTER_SPELLS_PREFIX
./generate_character-spells-ability.sh >> $OUTPUT_CHARACTER_SPELLS_PREFIX
cat $PATH_CHARACTER_SPELLCARD_SLOTS_EXPLANATION >> $OUTPUT_CHARACTER_SPELLS_PREFIX
./generate_spellcard-slots.sh 1 0 >> $OUTPUT_CHARACTER_SPELLS_PREFIX
