#!/bin/bash

# Project root
PROJECT_ROOT=$(dirname $(realpath $0))
echo "project root: $PROJECT_ROOT"


# Paths
PATH_CHARACTER_SPELLS=src/spells
PATH_CHARACTER_SPELL_ABILITIES=$PATH_CHARACTER_SPELLS/spells-ability.txt
PATH_CHARACTER_SPELL_ABILITIES_EXLPANATION=$PATH_CHARACTER_SPELLS/spells-ability-explanation.md
PATH_CHARACTER_SPELLCARD_SLOTS=$PATH_CHARACTER_SPELLS/spellcard-slots.txt
PATH_CHARACTER_SPELLCARD_SLOTS_EXPLANATION=$PATH_CHARACTER_SPELLS/spellcard-slots-explanation.md
OUTPUT_CHARACTER_SPELLS_PREFIX=doc_character-spells_level-1.md
